### ISSUE TITLE
Enchanting table has normal cap system

### ISSUE THREAD

**Issue by shouxd** [AmyMialee/no-enchantment-cap#1]
It'd be nice if uncapped enchantments could also appear on enchanting tables and villager trades

**Comment by shouxd** [comment]
also just realised /enchant has normal cap system too

**Comment by AmyMialee** [comment]
Making them show up on the table/from villagers is a lot harder to do, since at that point I have to try balance them in some way and I'm not sure what people would like.

I will work on the /enchant command though, thanks for mentioning it.

**Comment by AmyMialee** [comment]
/enchant support fully added (plus works on any item).
If you have more ideas and such for villagers/tables you can make it a new github issue or suggest it in the discord.
