### ISSUE TITLE
Villager and enchanting table idea

### ISSUE THREAD

**Issue by shouxd** [AmyMialee/no-enchantment-cap#2]
To enrich the mod a bit further, I think you could implement this into the enchanting table and villagers by giving enchantments with higher levels heavier weights so they're more and more difficult to get. Also I dont know if its possible, but if you could make the enchanting table require more levels for these higher level enchantments it'd be cool too.

**Comment by AmyMialee** [comment]
I do think this idea is alright but I feel it's a bit out of scope for this mod.
I think I'll leave this up to anyone who wants to make it it's own mod that uses this one.
