### ISSUE TITLE
[Bug?] Riptide not present in the configuration file

### ISSUE THREAD

**Issue by Derpitron** [AmyMialee/no-enchantment-cap#4]
I was trying to configure the max levels for a server's enchantments in the .toml file, but I had noticed that the riptide enchantment was not present. For now, I am using the global enchant limit, but it would be convenient if riptideCap was added. thanks!

**Comment by AmyMialee** [comment]
it'll be added next update

**Comment by AmyMialee** [comment]
Sorry for taking so long on this, ironically enough individual enchantment numbers are being cut so this is closed by extension.

**Comment by Derpitron** [comment]
Hey, thanks for the heads up.
